---
title: "Index"
author: "Murray Logan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  my_html_document:
    code_folding: none
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    theme: spacelab
    toc: yes
    toc_float: yes
    css: ../resources/tutorial_style.css
    template: ../resources/tutorial_template.html
  html_document:
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: textmat
    theme: spacelab
    toc: yes
    toc_float: yes
    css: ../public/resources/style.css
  pdf_document:
    df_print: default
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: tango
    latex_engine: xelatex
    number_sections: yes
    toc_depth: 2
  word_document:
    fig_caption: yes
    fig_height: 4
    fig_width: 4
    highlight: tango
    toc: yes
    toc_depth: 2
output_dir: "docs"
documentclass: article
fontsize: 12pt
mainfont: Arial
mathfont: LiberationMono
monofont: DejaVu Sans Mono
classoption: a4paper
bibliography: ../public/resources/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div style="font-size:16pt">
This page can be found at the following URL:<br>
https://pcinereus.github.io/SUYRs_docs/
</div>
   
# Tutorials
- [Introduction to git and github](http://www.flutterbys.com.au/stats/tut/tut19.1.html)
- [Introduction to reproducibility and Rmarkdown](reproducible_research_rmarkdown.html)
- [Reproducible research - containers](reproducible_research_docker.html)
<!--- [Introduction to data wrangling in R](http://www.flutterbys.com.au/stats/tut/tut2.4.html)-->
- [Introduction to data wrangling in R](data_manipulation.html)
- [Introduction to the Grammar of Graphics in R](grammar_of_graphics.html)
 
## Generalized linear models

- [GLM from first principles (nearly)](glm_part1.html)
- [Introduction to Generalized Additive Models (GAM)](gam_part1.html)

# Presentations

- [Course introduction (pres1.html)](pres1.html)
- [Introduction to git/github (pres19.1.html)](pres19.1.html)
- [Introduction to reproducibility and Rmarkdown (pres19.3.html)](pres19.3.html)
- [Introduction to data wrangling in R (pres2.4.html)](pres2.4.html)
- [Introduction to the Grammar of Graphics  R (pres5.2.html)](pres5.2.html)
- [Introduction to the Generalized linear modeling (pres7.1.html)](pres7.1.html)
- [More generalized linear modeling (pres7.2.html)](pres7.2.html)
- [Generalized linear mixed models (pres11.html)](pres11.html)
- [Generalized Additive Models (pres.8.html)](pres.8.html)
- [Regression Trees (pres9.html)](pres9.html)
- [Bayesian linear modelling (pres10.html)](pres10.html)
- [Intro to Multivariate (pres13.html)](pres13.html)
- [Multivariate: R-mode (pres14.html)](pres14.html)
- [Multivariate: Q-mode (pres15.html)](pres15.html)
 
